<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/my_robot_base.xacro" />
    
    <xacro:include filename="$(find robot_description)/my_robot_lidar.xacro" />
    
    <xacro:include filename="$(find robot_description)/imu.xacro" />

    <joint name="lidar_joint" type="fixed">
        <!-- <origin xyz="${base_radius-lidar_radius} 0 ${base_length+wheel_radius/3}" rpy="0 0 0" /> -->
        <origin xyz="0 0 ${base_length+wheel_radius/2}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="lidar_link" />
    </joint>
    
    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 ${wheel_radius}"/>
    </joint>
 
    <xacro:my_robot_base/>
    <xacro:lidar/>
    <xacro:imu_/>

</robot>
